/**
 * @author Timothe Watteau
 * @file Sensor.hpp
 * @date 25/09/2022
 * @brief Sensor class, retrieves data from the sensors processes them
 */

#ifndef AP4A_SENSOR_HPP
#define AP4A_SENSOR_HPP

#include "iostream"

class Sensor
{
private:
protected:
	std::string m_unit;
	int m_measuresPeriod;// time in seconds between each measure
	float m_minValue, m_maxValue; // minimum and maximum value generated by the sensor
	/**
	 * @brief Generates random value to simulate the sensor
	 * @param min minimum value
	 * @param max maximum value
	 * @return a random float between min and max
	 */
	float generateRandomValue(float min, float max);
public:
	/**
	 * @brief Orthodox canonical form constructors, destructor and affectation
	 */
	Sensor();
	Sensor(const Sensor& sensor);
	~Sensor();
	Sensor& operator=(const Sensor& sensor);

	/**
	 * @brief Retrieves data from the sensor
	 * @return the value of the sensor
	 */
	float getData();

	/**
	 * @brief Gives the measures period which is the interval of time between each measure
	 * @return the measures period
	 */
	int getMeasurePeriod();
	/**
	 * Gets the unit of the measures
	 * @return the string containing the unit of the measure of this sensor
	 */
	std::string getUnit();
};

#endif //AP4A_SENSOR_HPP
